### ISSUE TITLE
check this out

### ISSUE THREAD

**Issue by Guru322** [Alusius/Itsuki-Bot-3.0#32]
/home/runner/Hyzer-MD/system/database/LowDB/adapters/TextFile.js:2
const { Writer } = require('steno');
                   ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /home/runner/Hyzer-MD/node_modules/steno/lib/index.js from /home/runner/Hyzer-MD/system/database/LowDB/adapters/TextFile.js not supported.
Instead change the require of index.js in /home/runner/Hyzer-MD/system/database/LowDB/adapters/TextFile.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/runner/Hyzer-MD/system/database/LowDB/adapters/TextFile.js:2:20)
    at Object.<anonymous> (/home/runner/Hyzer-MD/system/database/LowDB/adapters/JSONFile.js:1:22)
    at Object.<anonymous> (/home/runner/Hyzer-MD/system/database/LowDB/index.js:2:8)
    at Object.<anonymous> (/home/runner/Hyzer-MD/hyzer.js:17:11) {
  code: 'ERR_REQUIRE_ESM'
}

**Comment by wffzy** [comment]
import * from "steno"
